### ISSUE TITLE
Duplicated genes in gene expression output from DBresult? 

### ISSUE THREAD

**Issue by rjoyce-projects** [MengjunWu/TCseq#5]
Hello,

Thank you for your work on TCseq, I am enjoying using it as a tool.
I have noticed that in the output from running DBresult there are genes with multiple differential expression values in the output matrix, in both the tutorial data that you provide and my own RNA-seq data.
If we use your dummy data for the example, after running this line:
`DBres<- DBresult(tca, group1 = "0h", group2 = c("24h","40h","72h"))`
Then extracting the DE list with this command:
`outputgenes <- as.data.frame(DBres$`24hvs0h`)`
If I look at the number of IDs in here there are 2751 peak IDs, if I only extract the unique IDs there are 917.
How can a gene/peak have multiple differential expression values in this way?

Thank you in advance for any help you can provide with this.

Rosanna

**Comment by MengjunWu** [comment]
Hi Rosanna,

I have run the example, and length(unique(outputgenes$id)) returns 2751, not sure how you extract the unique IDs?

Best,
Mengjun

**Comment by rjoyce-projects** [comment]
Thank you so much for your quick response it is much appreciated.
That is strange, when I run the same command I get 917 unique IDs output:
`length(unique(outputgenes$id))
[1] 917`

I will paste all of the commands that I have run to get to this point for clarity, my R is version 4.0.2 and  TCseq_1.12.0 and edgeR_3.30.3.
> data("experiment")
> data("countsTable")
> data("genomicIntervals")
> tca <- TCA(design = experiment, genomicFeature = genomicIntervals, counts = countsTable)
> tca <- DBanalysis(tca)
> DBres<- DBresult(tca, group1 = "0h", group2 = c("24h","40h","72h"))
> outputgenes <- as.data.frame(DBres$`24hvs0h`)
> length(outputgenes$id)
[1] 2751
> length(unique(outputgenes$id))
[1] 917

Can you see anything here that may have caused this issue of duplication? 
I will also add this example of peak1030 being present three times in the outputgenes dataframe for me, in case this helps:
> which(outputgenes$id == 'peak1030')
[1]  344 1261 2178
> outputgenes[c(344,1261,2178),]
     seqnames    start      end width strand     logFC       PValue          paj       id
344     chr16 90459088 90459522   435      * 0.7855288 3.737577e-03 3.738936e-02 peak1030
1261    chr16 90459088 90459522   435      * 2.0580435 1.912382e-16 6.922320e-15 peak1030
2178    chr16 90459088 90459522   435      * 3.1978085 9.721528e-40 7.865859e-39 peak1030

**Comment by MengjunWu** [comment]
There is an error when converting the result to GRangeList. For now, you could set result.type = "list" instead of result.type = "GRangesList", So use DBres<- DBresult(tca, group1 = "0h", group2 = c("24h","40h","72h"),  result.type = "list")

I will fix the error a bit later, thanks for spotting this

**Comment by rjoyce-projects** [comment]
Thank you so much your help Mengjun, the quick fix worked and now I have beautiful gene lists! I will close the issue as it has been resolved very quickly and efficiently!
